base_local_planner: "base_local_planner/TrajectoryPlannerROS"

TrajectoryPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  acc_lim_theta:  3.2
  max_vel_x: 0.8
  min_vel_x: 0.1 # 前進時の、最低速度
  max_vel_theta: 1.7
  min_vel_theta: -1.7
  min_in_place_vel_theta: 0.2

  holonomic_robot: true
  y_vels: [-0.5, -0.4, -0.3, -0.2, -0.1, 0.1, 0.2, 0.3, 0.4, 0.5]


  escape_vel: -0.1 # サンプリングした中に、有効なものがない場合に後退するときの速度

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true # ゴールに到達したら、その場回転のみ行うか

  # Forward Simulation Parameters
  sim_time: 2.0 # DWAのシミュレーションを何秒分やるか[s]
  sim_granularity: 0.02  # 軌道の粒度[m]
  angular_sim_granularity: 0.02 # 軌道の粒度[rad]
  vx_samples: 20 # xの速度方向のサンプリング数
  vtheta_samples: 50 # 回転方向のサンプリング数
  controller_frequency: 20.0 # 設定されていなければ、親のcontroller_frequencyを読み込む

  # Trajectory scoring parameters
  meter_scoring: false 
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale:  0.01

  heading_lookahead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8 
  dwa: true

  publish_cost_grid_pc: true
  global_frame_id: "odom"

  simple_attractor: false

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.25 # ロボットの振動が解除されたと判断するための移動距離
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1

