base_global_planner: "global_planner/GlobalPlanner"

GlobalPlanner:
   allow_unknown: true
   default_tolerance: 0.0
   use_dijkstra: true # ダイクストラ法か、A*アルゴリズムか
   use_quadratic: true
   use_grid_path: false
   outline_map: true
   orientation_mode: 2
   cost_factor: 0.55
   neutral_cost: 66
   visualize_potential: false
   publish_potential: true
   orientation_window_size: 10