global_frame: odom

rolling_window: true
width: 3.0
height: 3.0

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacles,               type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
