rarm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - r_shoulder_y_joint
    - r_shoulder_p_joint
    - r_elbow_joint
    - r_wrist_y_joint
    - r_wrist_p_joint
    - r_wrist_r_joint
    - r_hand_y_joint
lifter_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - knee_joint
    - ankle_joint
rhand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - r_thumb_joint

robot_interface_controllers: ['rarm', 'lifter']
